### ISSUE TITLE
Please publish version 4.1.2

### ISSUE THREAD

**Issue by mflorea** [webjars/less#19]
See https://github.com/less/less.js/tags . Thanks.

**Comment by jamesward** [comment]
Question for you... We have distributed a node and a web version of this, I think because they were different.  But now it seems they are they same.  Should / can we combine into a single artifact?

**Comment by mflorea** [comment]
I'm using the web version, but if this is now the same as the node version then I don't mind merging them in a single artifact, as it's easier to maintain and release. I can update the paths I use if needed. My only request is to keep the version in the path.

Thanks a lot for your work!

**Comment by jamesward** [comment]
Was working on this and realized that is is probably better if you can switch over to the NPM WebJar:
```
"org.webjars.npm" % "less" % "4.1.2"
```

Is that an option?  It is much easier to maintain that one and you can bump versions yourself.

**Comment by mflorea** [comment]
Indeed, I can do that. No reason to maintain two builds. Thanks!

**Comment by mflorea** [comment]
Actually there is a problem with the ``org.webjars.npm``: it brings some unwanted and useless transitive dependencies. I'll report an issue.

**Comment by mflorea** [comment]
I'm not sure where to report the issue. The problem is that dependencies from [``package-lock.json``](https://github.com/less/less.js/blob/v4.1.2/package-lock.json) that are marked for **development** with:

    "dev": true,

end up in the generated POM file (when the WebJar is published automatically from the NPM package). Moreover, the [``pacakge.json``](https://github.com/less/less.js/blob/v4.1.2/package.json) lists in this case only ``devDependencies`` which are needed only when building the project, not when using it. So they should end up in the POM file. Do you agree?

**Comment by jamesward** [comment]
Those are marked as `optional` in the pom.  But I'm not really sure what that does...  What is the issue you are having?

**Comment by mflorea** [comment]
Well, not all are marked as optional, see https://search.maven.org/artifact/org.webjars.npm/less/4.1.2/jar . The first 3 are not optional. The issue is that this brings useless transitive dependencies when I install it on my platform and I don't like installing jars that I don't use / need.

**Comment by jamesward** [comment]
Hmmm... I wonder if the less NPM package has a different `package.json` file.  I'll investigate.

**Comment by jamesward** [comment]
I'm releasing the Classic WebJar for this:
`org.webjars:less:4.1.2`

Should be available in Maven Central shortly.

**Comment by mflorea** [comment]
> In your build you could manually exclude the transitives.

Yes, that's what I did and it works fine.

> I'm releasing the Classic WebJar for this

Thanks, and sorry for giving you more work..
